name: Build and Push Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 2: Build and push frontend Docker image
      - name: Build and Push Frontend Docker Image
        run: |
          docker build ./frontend --file ./frontend/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      # Step 3: Build and push backend Docker image
      - name: Build and Push Backend Docker Image
        run: |
          docker build ./backend --file ./backend/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
